name: Android Testing CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Download dependencies
        run: ./gradlew build --scan --continue

      - name: Ensure system image is available
        run: |
          sdkmanager --install 'system-images;android-30;google_apis_playstore;x86' --channel=0
          sdkmanager --install 'emulator' --channel=0
          echo "y" | sdkmanager --licenses

      - name: Kill any running emulators
        run: |
          adb -e emu kill || true
          adb devices

      - name: Start Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis_playstore
          arch: x86
          profile: Nexus 6
          emulator-options: -no-boot-anim -no-audio -no-window
          disable-linux-hw-accel: true
          script: ./gradlew connectedAndroidTest
          emulator-boot-timeout: 1800

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }}

      - name: Terminate Emulator
        run: adb -s emulator-5554 emu kill
        if: always()
